---
- name: Create folders and set permission
  block:
    - name: Create bin directory
      file:
        path: ~/bin
        state: directory
    
    - name: Create backupinbox and backup dir
      file:
        path: "/{{ item }}"
        owner: backupuser
        group: backuplocalteam
        mode: "0750"
        state: directory
      loop:
        - backupinbox
        - backup