---
- name: Create ssh key
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_file: ".ssh/id_rsa_{{ansible_hostname}}_backupclient"

- name: Fetch the .pub keys
  fetch:
    src: "/root/.ssh/id_rsa_{{ansible_hostname}}_backupclient.pub"
    dest: roles/backupclient/files/
    flat: yes